routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


//Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin\\'], function(){
    Route::get('/', function (){
       return redirect('/admin/dashboard');
    });
    Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Auth\LoginController@login');

    Route::group(['middleware' => ['isVerified', 'can:admin']], function(){
        Route::post('logout', 'Auth\LoginController@logout')->name('logout');
        Route::get('dashboard', function (){
           return view('admin.dashboard');
        });

        Route::resource('users', 'UsersController');
        Route::resource('categories', 'CategoriesController');
        Route::resource('series', 'SeriesController');

        Route::get('reset-password', 'Auth\UserSethingsController@resetPassword')->name('reset-password');
        Route::put('reset-password', 'Auth\UserSethingsController@resetPasswordUpdate')->name('reset-password-put');
    });
});

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::get('email-verification/error', 'EmailVerificationController@getVerificationError')->name('email-verification.error');
Route::get('email-verification/check/{token}', 'EmailVerificationController@getVerification')->name('email-verification.check');

app/Http/Controllers/Admin/SeriesController.php
<?php

namespace CodeFlix\Http\Controllers\Admin;

use CodeFlix\Forms\SerieForm;
use CodeFlix\Models\Serie;
use CodeFlix\Repositories\SerieRepository;
use CodeFlix\Http\Controllers\Controller;
use FormBuilder;

class SeriesController extends Controller
{
    /**
     * @var SerieRepository
     */
    private $repository;

    /**
     * SeriesController constructor.
     */
    public function __construct(SerieRepository $repository)
    {
        $this->repository = $repository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $series = $this->repository->paginate();
        return view('admin.series.index', compact('series'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $form = FormBuilder::create(SerieForm::class, [
            'url' => route('admin.series.store'),
            'method' => 'POST'
        ]);
        return view('admin.series.create', compact('form'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return \Illuminate\Http\Response
     */
    public function store()
    {
        /** @var Form $form */
        $form = FormBuilder::create(SerieForm::class);
        $data = $form->getFieldValues();

        if (!$form->isValid()) {
            return redirect()->route('admin.series.create')->withErrors($form->getErrors())->withInput();
        }

        $this->repository->create($data);
        return redirect()->route('admin.series.index')->with('success', "Serie cadastrada com sucesso.");
    }

    /**
     * Display the specified resource.
     *
     * @param  Serie  $series
     * @return \Illuminate\Http\Response
     */
    public function show(Serie $series)
    {
        return view('admin.series.show', compact('series'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Serie $series
     * @return \Illuminate\Http\Response
     */
    public function edit(Serie $series)
    {
        $form = FormBuilder::create(SerieForm::class, [
            'method' => "PUT",
            'url' => route('admin.series.update', $series->id),
            'model' => $series
        ]);

        return view('admin.series.edit', compact('form'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param $id
     * @return \Illuminate\Http\Response
     */
    public function update($id)
    {
        /** @var Form $form */
        $form = FormBuilder::create(SerieForm::class);
        if (!$form->isValid()) {
            return redirect()->route('admin.series.edit', $id)->withErrors($form->getErrors())->withInput();
        }
        $data = $form->getFieldValues();
        $this->repository->update($data, $id);

        return redirect()->route('admin.series.index')->with('success', "Serie alterada com sucesso.");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->repository->delete($id);
        return redirect()->route('admin.series.index')->with('success', "Serie excluida com sucesso.");
    }
}

resources/views/admin/series/create.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container">

        <div class="page-header">
            <h2>Nova serie</h2>
        </div>

        @if(Session::has('error'))
            <div class="alert alert-danger fade in">
                {{ Session::get('error') }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        @endif

        <div class="row">
            <div class="col-md-12">
                {!! form($form->add('salvar', 'submit', [
                    'attr' => ['class' => 'btn btn-primary btn-block'],
                    'label' => '<span class="glyphicon glyphicon-floppy-disk"></span> Salvar'
                ])) !!}
            </div>
        </div>
    </div>
@endsection

resources/views/admin/series/edit.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container">

        <div class="page-header">
            <h2>Alterar serie</h2>
        </div>

        @if(Session::has('error'))
            <div class="alert alert-danger fade in">
                {{ Session::get('error') }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        @endif

        <div class="row">
            <div class="col-md-12">
                {!! form($form->add('salvar', 'submit', [
                    'attr' => ['class' => 'btn btn-primary btn-block'],
                    'label' => '<span class="glyphicon glyphicon-floppy-disk"></span> Salvar'
                ])) !!}
            </div>
        </div>
    </div>
@endsection

resources/views/admin/series/index.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container">
        <div class="page-header">
            <h2>Series
                <small>| <a href="{{ route('admin.series.create') }}">Nova Serie</a></small>
            </h2>
        </div>

        @if(Session::has('success'))
            <div class="alert alert-success fade in">
                {{ Session::get('success') }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        @endif

        <table class="table table-striped">
            <thead>
            <tr>
                <th width="5%" rowspan>#</th>
                <th>Titulo</th>
                <th>Descrição</th>
                <th width="8%">Ações</th>
            </tr>
            </thead>
            <tbody>
            @foreach($series as $serie)
                <tr>
                    <td>{{ $serie->id }}</td>
                    <td>{{ $serie->title }}</td>
                    <td>{{ $serie->description }}</td>
                    <td>
                        <div class="btn-group btn-group-xs">
                            <a href="{{ route('admin.series.edit', $serie->id) }}" class="btn btn-primary"><span class="glyphicon glyphicon-pencil"></span></a>
                            <a href="{{ route('admin.series.show', $serie->id) }}" class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span></a>
                        </div>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>

        {!! $series->render() !!}
    </div>
@endsection

resources/views/admin/series/show.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container">

        <div class="page-header">
            <h2>Dados da serie: <strong>{{ $series->name }}</strong></h2>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h4 class="panel-title">Informações da categoria</h4>
                    </div>

                    <table class="table table-bordered">
                        <tbody>
                        <tr>
                            <th class="text-center" scope="row">#</th>
                            <td>{{ $series->id }}</td>
                        </tr>
                        <tr>
                            <th width="5%" scope="row">Nome:</th>
                            <td>{{ $series->title }}</td>
                        </tr>
                        <tr>
                            <th width="5%" scope="row">Descrição:</th>
                            <td>{{ $series->description }}</td>
                        </tr>
                        </tbody>
                    </table>
                </div>

            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <hr>
                <div class="btn-group">
                    <a href="{{ route('admin.categories.edit', $series->id) }}" class="btn btn-primary"><span class="glyphicon glyphicon-pencil"></span> Editar</a>
                    <a href="{{ route('admin.categories.destroy', $series->id) }}" class="btn btn-danger" onclick="event.preventDefault(); document.getElementById('form-delete').submit()"><span class="glyphicon glyphicon-trash"></span> Excluir</a>
                    @php $formDelete = FormBuilder::plain(['route' => ['admin.categories.destroy', $series->id], 'id' => 'form-delete', 'method' => 'DELETE', 'style' => 'display:none']) @endphp
                    {!! form($formDelete) !!}
                </div>
            </div>
        </div>
    </div>
@endsection