routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


//Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin\\'], function(){
    Route::get('/', function (){
       return redirect('/admin/dashboard');
    });
    Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Auth\LoginController@login');

    Route::group(['middleware' => ['isVerified', 'can:admin']], function(){
        Route::post('logout', 'Auth\LoginController@logout')->name('logout');
        Route::get('dashboard', function (){
           return view('admin.dashboard');
        });

        Route::resource('users', 'UsersController');
        Route::resource('categories', 'CategoriesController');
        Route::resource('series', 'SeriesController');

        Route::get('reset-password', 'Auth\UserSethingsController@resetPassword')->name('reset-password');
        Route::put('reset-password', 'Auth\UserSethingsController@resetPasswordUpdate')->name('reset-password-put');
    });
});

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::get('email-verification/error', 'EmailVerificationController@getVerificationError')->name('email-verification.error');
Route::get('email-verification/check/{token}', 'EmailVerificationController@getVerification')->name('email-verification.check');

app/Models/User.php
<?php

namespace CodeFlix\Models;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

class User extends Authenticatable implements Transformable
{
    use TransformableTrait, Notifiable;

    const ROLE_ADMIN = 1;
    const ROLE_CLIENT = 2;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'role',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public static function generatePassword($password = null)
    {
        return !$password ? bcrypt(str_random(8)) : bcrypt($password);
    }

}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace CodeFlix\Http\Controllers\Admin;

use CodeFlix\Forms\ResetPasswordForm;
use CodeFlix\Forms\UserForm;
use CodeFlix\Models\User;
use CodeFlix\Http\Controllers\Controller;
use CodeFlix\Repositories\UserRepository;
use Illuminate\Http\Request;
use Kris\LaravelFormBuilder\Form;
use FormBuilder;

class UsersController extends Controller
{
    /**
     * @var UserRepository
     */
    private $repository;

    /**
     * UsersController constructor.
     * @param UserRepository $repository
     */
    public function __construct(UserRepository $repository)
    {
        $this->repository = $repository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = $this->repository->paginate();
        return view('admin.users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $form = \FormBuilder::create(UserForm::class, [
            'method' => "POST",
            'url' => route('admin.users.store')
        ]);
        return view('admin.users.create', compact('form'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return \Illuminate\Http\Response
     */
    public function store()
    {
        /** @var Form $form */
        $form = FormBuilder::create(UserForm::class);
        $data = $form->getFieldValues();

        if (!$form->isValid()) {
            return redirect()->route('admin.users.create')->withErrors($form->getErrors())->withInput();
        }

        $this->repository->create($data);
        return redirect()->route('admin.users.index')->with('success', "Usuário cadastrado com sucesso.");
    }

    /**
     * Display the specified resource.
     *
     * @param  \CodeFlix\Models\User $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return view('admin.users.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \CodeFlix\Models\User $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $form = \FormBuilder::create(UserForm::class, [
            'method' => "PUT",
            'url' => route('admin.users.update', ['user' => $user->id]),
            'model' => $user
        ]);

        return view('admin.users.edit', compact('form'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \CodeFlix\Models\User $user
     * @return \Illuminate\Http\Response
     */
    public function update($id)
    {
        /** @var Form $form */
        $form = FormBuilder::create(UserForm::class, [
            'data' => ['id' => $id]
        ]);
        if (!$form->isValid()) {
            return redirect()->route('admin.users.create')->withErrors($form->getErrors())->withInput();
        }

        $data = array_except($form->getFieldValues(), ['role', 'password']);
        $this->repository->update($data, $id);

        return redirect()->route('admin.users.index')->with('success', "Usuário alterado com sucesso.");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \CodeFlix\Models\User $user
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->repository->delete($id);
        return redirect()->route('admin.users.index')->with('success', "Usuário excluido com sucesso.");
    }

}

resources/views/admin/users/create.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container">

        <div class="page-header">
            <h2>Novo usuário</h2>
        </div>

        @if(Session::has('error'))
            <div class="alert alert-danger fade in">
                {{ Session::get('error') }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        @endif

        <div class="row">
            <div class="col-md-12">
                {!! form($form->add('salvar', 'submit', [
                    'attr' => ['class' => 'btn btn-primary btn-block'],
                    'label' => '<span class="glyphicon glyphicon-floppy-disk"></span> Salvar'
                ])) !!}
            </div>
        </div>
    </div>
@endsection

resources/views/admin/users/edit.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container">

        <div class="page-header">
            <h2>Novo usuário</h2>
        </div>

        @if(Session::has('error'))
            <div class="alert alert-danger fade in">
                {{ Session::get('error') }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        @endif

        <div class="row">
            <div class="col-md-12">
                {!! form($form->add('salvar', 'submit', [
                    'attr' => ['class' => 'btn btn-primary btn-block'],
                    'label' => '<span class="glyphicon glyphicon-floppy-disk"></span> Salvar'
                ])) !!}
            </div>
        </div>
    </div>
@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container">
        <div class="page-header">
            <h2>Listagem de usuários <small><a href="{{route('admin.users.create')}}"><span class="glyphicon glyphicon-plus"></span> Novo usuário</a></small></h2>
        </div>
        @if(Session::has('success'))
            <div class="alert alert-success fade in">
                {{ Session::get('success') }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        @endif

        <table class="table table-striped table-bordered">
            <thead>
            <tr>
                <th>#</th>
                <th>Nome</th>
                <th>E-mail</th>
                <th>Ações</th>
            </tr>
            </thead>
            <tbody>
            @foreach($users as $user)
                <tr>
                    <td>{{ $user->id }}</td>
                    <td>{{ $user->name }}</td>
                    <td>{{ $user->email }}</td>
                    <td width="7%" class="text-center" rowspan>
                        <div class="btn-group btn-group-xs">
                            <a href="{{route('admin.users.edit', $user->id)}}" class="btn btn-primary"><span class="glyphicon glyphicon-pencil"></span></a>
                            <a href="{{ route('admin.users.show', $user->id) }}" class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span></a>
                        </div>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>

        {!! $users->render() !!}
    </div>
@endsection

resources/views/admin/users/show.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container">

        <div class="page-header">
            <h2>Dados do usuário: <strong>{{ $user->name }}</strong></h2>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h4 class="panel-title">Informações do Usuário</h4>
                    </div>

                    <table class="table table-bordered">
                        <tbody>
                        <tr>
                            <th class="text-center" scope="row">#</th>
                            <td>{{ $user->id }}</td>
                        </tr>
                        <tr>
                            <th width="5%" scope="row">Nome:</th>
                            <td>{{ $user->name }}</td>
                        </tr>
                        <tr>
                            <th scope="row">E-mail:</th>
                            <td>{{ $user->email }}</td>
                        </tr>
                        </tbody>
                    </table>
                </div>

            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <hr>
                <div class="btn-group">
                    <a href="{{ route('admin.users.edit', $user->id) }}" class="btn btn-primary"><span class="glyphicon glyphicon-pencil"></span> Editar</a>
                    <a href="{{ route('admin.users.destroy', $user->id) }}" class="btn btn-danger" onclick="event.preventDefault(); document.getElementById('form-delete').submit()"><span class="glyphicon glyphicon-trash"></span> Excluir</a>
                    @php $formDelete = FormBuilder::plain(['route' => ['admin.users.destroy', $user->id], 'id' => 'form-delete', 'method' => 'DELETE', 'style' => 'display:none']) @endphp
                    {!! form($formDelete) !!}
                </div>
            </div>
        </div>
    </div>
@endsection